version: "2"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/code
            - ./docker/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php

    php:
        build: docker/php
        volumes:
            - .:/code
        links:
            - postgres

    postgres:
        image: postgres:9.3
        ports:
            - "5433:5432"
